### ISSUE TITLE
No tengo acceso a los settings

### ISSUE THREAD

**Issue by eduardobritosan** [ULL-ESIT-GRADOII-PL/conversor-de-temperatura-simple-javier-eduardo#1]
No hay acceso a los settings del proyecto.

**Comment by crguezl** [comment]
Hazle un fork a un repo tuyo y así tendrás acceso a los settings, luego haces el pull request y el merge

**Comment by eduardobritosan** [comment]
Perfecto, arreglado, muchas gracias!
